#!/bin/bash

CONFY_DIR="$(dirname "$(realpath "$BASH_SOURCE[0]")")"

if [ "$CONFY_DIR" == "/usr/local/bin" ]; then
    CONFY_SCRIPT="$(realpath "/usr/local/bin/confy")"
    CONFY_DIR="$(dirname "$CONFY_SCRIPT")"
fi

"$CONFY_DIR/__python" "$CONFY_DIR/confy.py" "$@"